export const MEETING_LIST_REQUEST = 'MEETING_LIST_REQUEST';
export const MEETING_LIST_SUCCESS = 'MEETING_LIST_SUCCESS';
export const MEETING_LIST_FAIL = 'MEETING_LIST_FAIL';

export const MEETING_UPDATE_REQUEST = 'MEETING_UPDATE_REQUEST';
export const MEETING_UPDATE_SUCCESS = 'MEETING_UPDATE_SUCCESS';
export const MEETING_UPDATE_FAIL = 'MEETING_UPDATE_FAIL';
export const MEETING_UPDATE_RESET = 'MEETING_UPDATE_RESET';

export const MEETING_DELETE_REQUEST = 'MEETING_DELETE_REQUEST';
export const MEETING_DELETE_SUCCESS = 'MEETING_DELETE_SUCCESS';
export const MEETING_DELETE_FAIL = 'MEETING_DELETE_FAIL';

export const MEETING_DETAILS_REQUEST = 'MEETING_DETAILS_REQUEST';
export const MEETING_DETAILS_SUCCESS = 'MEETING_DETAILS_SUCCESS';
export const MEETING_DETAILS_FAIL = 'MEETING_DETAILS_FAIL';

export const MEETING_CREATE_REQUEST = 'MEETING_CREATE_REQUEST';
export const MEETING_CREATE_SUCCESS = 'MEETING_CREATE_SUCCESS';
export const MEETING_CREATE_FAIL = 'MEETING_CREATE_FAIL';
export const MEETING_CREATE_RESET = 'MEETING_CREATE_RESET';
